services:
  - type: web
    name: saberpro-parcial-java
    env: docker
    plan: free
    autoDeploy: false
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: render
      - key: PORT
        value: 8080
